# Generated by Django 5.2.3 on 2025-06-12 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'degree',
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'discipline',
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5, unique=True)),
            ],
            options={
                'db_table': 'office',
            },
        ),
        migrations.CreateModel(
            name='OtherActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'other_activity',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'position',
            },
        ),
        migrations.CreateModel(
            name='TeachingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'db_table': 'teaching_type',
            },
        ),
        migrations.CreateModel(
            name='WorkTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.FloatField(unique=True)),
            ],
            options={
                'db_table': 'work_time',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('third_name', models.CharField(blank=True, max_length=20, null=True)),
                ('birth_date', models.DateField()),
                ('email', models.CharField(max_length=30, unique=True)),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('degree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.degree')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.office')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.position')),
                ('work_time', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.worktime')),
            ],
            options={
                'db_table': 'professor',
            },
        ),
        migrations.CreateModel(
            name='ProfessorOtherActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.otheractivity')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.professor')),
            ],
            options={
                'db_table': 'professor_other_activity',
                'constraints': [models.UniqueConstraint(fields=('professor', 'activity'), name='unique_professor_activity')],
            },
        ),
        migrations.CreateModel(
            name='ProfessorDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.discipline')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.professor')),
                ('teaching_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.teachingtype')),
            ],
            options={
                'db_table': 'professor_discipline',
                'constraints': [models.UniqueConstraint(fields=('professor', 'discipline', 'teaching_type'), name='unique_professor_discipline_teaching_type')],
            },
        ),
    ]
